name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/texlive-action@v3
        with:
          run: make build

      - name: Rename PDF
        run: mv main.pdf cv.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cv
          path: .

      - name: Add redirect index.html
        run: echo '<meta http-equiv="refresh" content="0; url=./cv.pdf">' > index.html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true

